In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv("2020_US_Region_Mobility_Report.csv")
df

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727714,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,2020-11-23,NaN,NaN,NaN,NaN,-23.0,NaN
727715,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,2020-11-24,NaN,NaN,NaN,NaN,-21.0,NaN
727716,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,2020-11-25,NaN,NaN,NaN,NaN,-27.0,NaN
727717,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,2020-11-26,NaN,NaN,NaN,NaN,-73.0,NaN
727718,US,United States,Wyoming,Weston County,NaN,NaN,56045.0,2020-11-27,NaN,NaN,NaN,NaN,-58.0,NaN

In [3]:
clean_df = df.rename(columns={"country_region_code": "country_code",
                             "country_region": "country",
                             "sub_region_1": "state",
                             "sub_region_2": "county",
                             "metro_area": "metro_area",
                             "iso_3166_2_code": "territory_subdivisions",
                             "census_fips_code": "census_fips_code",
                             "date": "date",
                             "retail_and_recreation_percent_change_from_baseline": "retail_and_recreation_percent_change_from_baseline",
                             "grocery_and_pharmacy_percent_change_from_baseline": "grocery_and_pharmacy_percent_change_from_baseline",
                             "parks_percent_change_from_baseline": "parks_percent_change_from_baseline",
                             "transit_stations_percent_change_from_baseline": "transit_stations_percent_change_from_baseline",
                             "workplaces_percent_change_from_baseline": "workplaces_percent_change_from_baseline",
                             "residential_percent_change_from_baseline": "residential_percent_change_from_baseline",})
clean_df.head()

,country_code,country,state,county,metro_area,territory_subdivisions,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,US,United States,NaN,NaN,NaN,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0

In [4]:
clean_df = clean_df[[
    "state",
    "county",
    "date",
    "retail_and_recreation_percent_change_from_baseline",
    "grocery_and_pharmacy_percent_change_from_baseline",
    "parks_percent_change_from_baseline",
    "transit_stations_percent_change_from_baseline",
    "workplaces_percent_change_from_baseline",
    "residential_percent_change_from_baseline"
]]
clean_df.head()

,state,county,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,NaN,NaN,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
1,NaN,NaN,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
2,NaN,NaN,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
3,NaN,NaN,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
4,NaN,NaN,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0

In [5]:
clean_df = clean_df.dropna(subset=['state'])
clean_df

,state,county,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
289,Alabama,NaN,2020-02-15,5.0,2.0,39.0,7.0,2.0,-1.0
290,Alabama,NaN,2020-02-16,0.0,-2.0,-7.0,3.0,-1.0,1.0
291,Alabama,NaN,2020-02-17,3.0,0.0,17.0,7.0,-17.0,4.0
292,Alabama,NaN,2020-02-18,-4.0,-3.0,-11.0,-1.0,1.0,2.0
293,Alabama,NaN,2020-02-19,4.0,1.0,6.0,4.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
727714,Wyoming,Weston County,2020-11-23,NaN,NaN,NaN,NaN,-23.0,NaN
727715,Wyoming,Weston County,2020-11-24,NaN,NaN,NaN,NaN,-21.0,NaN
727716,Wyoming,Weston County,2020-11-25,NaN,NaN,NaN,NaN,-27.0,NaN
727717,Wyoming,Weston County,2020-11-26,NaN,NaN,NaN,NaN,-73.0,NaN
727718,Wyoming,Weston County,2020-11-27,NaN,NaN,NaN,NaN,-58.0,NaN

In [25]:
indiana_df = clean_df[clean_df['state'] == "Indiana"]
indiana_df

,state,county,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
167818,Indiana,NaN,2020-02-15,9.0,4.0,16.0,7.0,0.0,-1.0
167819,Indiana,NaN,2020-02-16,8.0,3.0,34.0,5.0,1.0,-1.0
167820,Indiana,NaN,2020-02-17,5.0,-3.0,-4.0,2.0,-13.0,4.0
167821,Indiana,NaN,2020-02-18,1.0,-1.0,3.0,4.0,2.0,0.0
167822,Indiana,NaN,2020-02-19,4.0,0.0,9.0,5.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...
192824,Indiana,Whitley County,2020-11-25,18.0,36.0,NaN,NaN,-35.0,10.0
192825,Indiana,Whitley County,2020-11-26,-68.0,NaN,NaN,NaN,-87.0,27.0
192826,Indiana,Whitley County,2020-11-27,-18.0,-15.0,NaN,NaN,-69.0,22.0
192827,Indiana,Whitley County,2020-11-28,-10.0,NaN,NaN,NaN,-25.0,NaN
192828,Indiana,Whitley County,2020-11-29,-11.0,-2.0,NaN,NaN,-13.0,NaN

In [26]:
indiana_df = indiana_df.dropna(subset=['county'])

In [27]:
indiana_df = indiana_df.reset_index(drop=True)

In [29]:
indiana_df

,state,county,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,Indiana,Adams County,2020-02-15,5.0,-11.0,NaN,NaN,2.0,NaN
1,Indiana,Adams County,2020-02-16,7.0,NaN,NaN,NaN,1.0,NaN
2,Indiana,Adams County,2020-02-17,3.0,-10.0,NaN,NaN,-5.0,3.0
3,Indiana,Adams County,2020-02-18,7.0,-7.0,NaN,NaN,1.0,0.0
4,Indiana,Adams County,2020-02-19,4.0,-6.0,NaN,NaN,2.0,0.0
...,...,...,...,...,...,...,...,...,...
24717,Indiana,Whitley County,2020-11-25,18.0,36.0,NaN,NaN,-35.0,10.0
24718,Indiana,Whitley County,2020-11-26,-68.0,NaN,NaN,NaN,-87.0,27.0
24719,Indiana,Whitley County,2020-11-27,-18.0,-15.0,NaN,NaN,-69.0,22.0
24720,Indiana,Whitley County,2020-11-28,-10.0,NaN,NaN,NaN,-25.0,NaN
24721,Indiana,Whitley County,2020-11-29,-11.0,-2.0,NaN,NaN,-13.0,NaN

In [28]:
indiana_df2 = indiana_df.dropna(how='any')